name: hisensor
description: MQTT client for Hisense TVs
version: 0.1.0
homepage: https://github.com/olankens/hisensor

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  mqtt_client: ^9.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/
